/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApiCredentials: typeof import('./components/ApiCredentials.vue')['default']
    AppNavbar: typeof import('./components/AppNavbar.vue')['default']
    ConversionForm: typeof import('./components/ConversionForm.vue')['default']
    FilesTable: typeof import('./components/FilesTable.vue')['default']
    FileUploader: typeof import('./components/FileUploader.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HistoryTable: typeof import('./components/HistoryTable.vue')['default']
    PasswordInput: typeof import('./components/PasswordInput.vue')['default']
    PricingTable: typeof import('./components/PricingTable.vue')['default']
    ProductCaroulsel: typeof import('./components/ProductCaroulsel.vue')['default']
    ProfileCard: typeof import('./components/ProfileCard.vue')['default']
    PublicConversionForm: typeof import('./components/PublicConversionForm.vue')['default']
    ResetPassword: typeof import('./components/ResetPassword.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignupForm: typeof import('./components/SignupForm.vue')['default']
  }
}
